Thierry Maillard - 29/7/2015 - 4/7/2020

=======================
Installations de base :
=======================

Python3 :
Ref : https://www.python.org
https://www.python.org/downloads/
Télécharger un paquet précompilé

        if problem urllib ssl.SSLError :
        Launch "Install Certificates.command" located in Python installation directory :
        sudo /Applications/Python\ 3.6/Install\ Certificates.command


Pip :
Ref : https://pypi.python.org/pypi/pip
curl -O https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py
su
cd /Users/thierry/Documents/informatique/logiciels/python/python3
python3 get-pip.py

matplotlib : 19/10/2015
su
sudo python3 -m pip install matplotlib
Successfully installed matplotlib-1.4.3 nose-1.3.7 numpy-1.10.1 pyparsing-2.0.3 python-dateutil-2.4.2 pytz-2015.6 six-1.10.0

===============================
Lancement programmes :
===============================
Voir README

===============================
Problèmes et solution :
===============================
- Erreur Détection nom de département
	AssertionError: recupNomDepStr() nom de département vide dans article :
		 Beaupréau
	Il s’agit d’une commune fusionnée avec une autre, ici : Beaupréau-en-Mauges
	La base Alize2 n’a pas basculé sur les nouvelles communes
	Solution : ignorer les anciennes communes.
		Les supprimer des listes
	Ref : https://fr.wikipedia.org/wiki/Catégorie:Commune_disparue_au_XXIe_siècle
	Mettre les nouvelles communes dans les listes

===============================
Outils de qualité logicielle
===============================

Py.test :
Ref : https://pytest.org
python3 -m pip install -U pytest
Utilisation Py.test sous compte user : 168 tests en V1.2.0
Jouer tous les tests unitaires : python3 -m pytest .
Afficher stdout :  python3 -m pytest -s .
Jouer un test unitaire spécifique : python3 -m pytest -k letestajouer .
Utiliser unittest.sh

Evaluer la couverture de test globale :
Analyse run Py.test : python3 -m coverage run -m pytest .
Affichage résultats : python3 -m coverage report > qualite/couv_test_verbose.txt

Pylint :
Ref : http://www.pylint.org
Install : python3 -m pip install pylint
Usage : python3 -m pylint xxx.py
Désactiver un message : invalid-name (C0103) et tout analyser :
python3 -m pylint --disable=invalid-name *.py > qualite/resu_pylint.txt

Problème pylint pour genereCode1Goupement.py et genereCode1Ville.py
RecursionError: maximum recursion depth exceeded
L'analyse s'arrête après un de ces fichier.
Malgré mes efforts (fractionnement des sources), je ne trouve pas pourquoi.
Solution :
- soumettre genereCode1Goupement.py et genereCode1Ville.py individuellement à pylint
- renommer ces 2 fichiers : ext + .0
- python3 -m pylint --disable=invalid-name *.py > qualite/resu_pylint.txt


Pycoverage :
Ref : https://coverage.readthedocs.io/en/latest/
Install : python3 -m pip install coverage
coverage run -m pytest  unittest
coverage report -m > qualite/couv_test_verbose.txt

